name: Build

on:
  push:
    tags:
      - "*"

#on:
#  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'info'
#        type: choice
#        options:
#        - info
#        - warning
#        - debug

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - id: build
        name: build apk
        run: |
          ls -al
          ls /usr/local/lib/android/sdk/build-tools/
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode --wrap=0 > keystore.jks
          export KEY_STORE_FILE='../keystore.jks'
          export KEY_ALIAS=${{ secrets.ALIAS }}
          export KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}
          export KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          chmod +x gradlew
          ./gradlew assembleRelease
          ls -al app/build/outputs/apk/release/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*-arm64-v8a-release.apk"
          # github auto generate temporary token
          token: ${{ github.token }}
          generateReleaseNotes: true
          makeLatest: latest
          allowUpdates: true
